<a href="https://colab.research.google.com/github/laurenbishop0000/brushup_2025/blob/main/Colab_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to import data into Google Collab

## Option 1: mounting google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
# adjust the link in accordance to where you uploaded the csv - make sure that it's not a version you opened in google sheets but the original csv simply uploaded

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/EconAI_private/Teaching/Brushup_DSDM/data/WB_pop_clean.csv')

#df = pd.read_csv('/content/drive/MyDrive/WB_pop_clean.csv')

In [ ]:
df

,Series Name,Series Code,Country Name,Country Code,2001,2002,2003,2011,2012,2013,2021,2022,2023
0,"Population, total",SP.POP.TOTL,Afghanistan,AFG,19688632,21000256,22645130,29249157,30466479,31541209,40099462,41128771,42239854
1,"Population, total",SP.POP.TOTL,Albania,ALB,3060173,3051010,3039616,2905195,2900401,2895092,2811666,2777689,2745972
2,"Population, total",SP.POP.TOTL,Algeria,DZA,31200985,31624696,32055883,36543541,37260563,38000626,44177969,44903225,45606480
3,"Population, total",SP.POP.TOTL,American Samoa,ASM,58324,58177,57941,54310,53691,52995,45035,44273,43914
4,"Population, total",SP.POP.TOTL,Andorra,AND,67820,70849,73907,70567,71013,71367,79034,79824,80088
...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,"Population, total",SP.POP.TOTL,West Bank and Gaza,PSE,2997784,3075373,3154969,3882986,3979998,4076708,4922749,5043612,5165775
214,"Population, total",SP.POP.TOTL,"Yemen, Rep.",YEM,19143457,19660653,20188799,25475610,26223391,26984002,32981641,33696614,34449825
215,"Population, total",SP.POP.TOTL,Zambia,ZMB,10191964,10508294,10837973,14265814,14744658,15234976,19473125,20017675,20569737
216,"Population, total",SP.POP.TOTL,Zimbabwe,ZWE,11910978,11984644,12075828,13025785,13265331,13555422,15993524,16320537,16665409
217,"Population, total",SP.POP.TOTL,World,WLD,6226487141,6308284566,6389592840,7053988749,7141430933,7229458453,7888963821,7951595433,8024997028



```
# This is formatted as code
```

## Option 2: via GoogleCredentials

In [ ]:
# Install the required libraries
#!pip install gspread google-auth

# Import libraries
import gspread
from gspread_dataframe import get_as_dataframe
from google.colab import auth
from oauth2client.client import GoogleCredentials
from google.auth import default
import pandas as pd

# Authenticate and create a client
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

In [ ]:
# take the excel spreadsheet with mutiple worksheet tabs that I shared, upload/ add it to your drive and OPEN IT IN & SAVE AS GOOGLE SHEET.
# then paste the link to that sheet here:

#spreadsheet_url = 'https://docs.google.com/spreadsheets/d/13IZxy4XwbQ7dXxGmj0ODostAD_mJf9S3rhHXrdYtO0I/edit?gid=238107633#gid=238107633'
#spreadsheet_url =  'https://docs.google.com/spreadsheets/d/13IZxy4XwbQ7dXxGmj0ODostAD_mJf9S3rhHXrdYtO0I/edit?gid=0#gid=0'
spreadsheet_url =  'https://docs.google.com/spreadsheets/d/13IZxy4XwbQ7dXxGmj0ODostAD_mJf9S3rhHXrdYtO0I/edit?usp=sharing'

# Open the spreadsheet
spreadsheet = gc.open_by_url(spreadsheet_url)

In [ ]:
# Get all the worksheet objects (tabs) in the spreadsheet
worksheets = spreadsheet.worksheets()

# Create a dictionary of DataFrames for each sheet
dfs = {}
for sheet in worksheets:
    sheet_name = sheet.title
    df = get_as_dataframe(sheet)
    dfs[sheet_name] = df

# Print the names of the sheets and their respective DataFrame head
for sheet_name, df in dfs.items():
    print(f"name of sheet: {sheet_name}")
    #print(df.head())  # Show first few rows of each DataFrame - NB it contains tons of NaNs

name of sheet: name1
name of sheet: name2

In [ ]:
df1 = dfs['name1']
print('initial shape:', df1.shape)
df1 = df1.loc[:,~df1.columns.str.match("Unnamed")]
print('after removing unndamed columns: ', df1.shape)
df1 = df1.dropna()
print('after removing rows with NaNs: ', df1.shape)
df1

initial shape: (4, 3)
after removing unndamed columns:  (4, 3)
after removing rows with NaNs:  (4, 3)

     col_1  col_2  col_3
0     some   33.0    2.4
1  random    44.0    3.5
2    text    55.0    4.6
3     data   66.0    5.7

In [ ]:
df2 = dfs['name2']
print('initial shape:', df2.shape)
df2 = df2.loc[:,~df2.columns.str.match("Unnamed")]
print('after removing unndamed columns: ', df2.shape)
df2 = df2.dropna()
print('after removing rows with NaNs: ', df2.shape)
df2

initial shape: (4, 3)
after removing unndamed columns:  (4, 3)
after removing rows with NaNs:  (4, 3)

   col_1  col_2  col_3
0     a    77.0    1.2
1    bit   88.0    6.7
2  more    99.0    7.8
3   text  100.0    8.9

## Option 3: via external database - Dropbox

In [ ]:
# NB, you need to change the =0 at the end of the original linkto =1

more_data = pd.read_csv('https://www.dropbox.com/scl/fi/izex86axu76nlyv049idr/WB_more_data.csv?rlkey=68cm1vd4yzk8ea7i77b5qk1db&st=s9hdvdgs&dl=1')
more_data

,Series Name,Series Code,Country Name,Country Code,2001,2002,2003,2011,2012,2013,2021,2022,2023
0,"Population, total",SP.POP.TOTL,Afghanistan,AFG,19688632,21000256,22645130,29249157,30466479,31541209,40099462,41128771,42239854
1,"Population, total",SP.POP.TOTL,Albania,ALB,3060173,3051010,3039616,2905195,2900401,2895092,2811666,2777689,2745972
2,"Population, total",SP.POP.TOTL,Algeria,DZA,31200985,31624696,32055883,36543541,37260563,38000626,44177969,44903225,45606480
3,"Population, total",SP.POP.TOTL,American Samoa,ASM,58324,58177,57941,54310,53691,52995,45035,44273,43914
4,"Population, total",SP.POP.TOTL,Andorra,AND,67820,70849,73907,70567,71013,71367,79034,79824,80088
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,"GNI, Atlas method (current US$)",NY.GNP.ATLS.CD,Virgin Islands (U.S.),VIR,..,..,..,..,..,..,..,..,..
1081,"GNI, Atlas method (current US$)",NY.GNP.ATLS.CD,West Bank and Gaza,PSE,4093011325.58684,3665299323.09048,4328972370.19645,11175431624.7764,12759178234.8466,14150619727.8472,21000435319.6176,23810735951.7193,21800691653.9541
1082,"GNI, Atlas method (current US$)",NY.GNP.ATLS.CD,"Yemen, Rep.",YEM,8683416697.21847,9543316523.25537,10362910322.8485,25694362119.0205,30836220079.2874,36138877868.4285,..,..,..
1083,"GNI, Atlas method (current US$)",NY.GNP.ATLS.CD,Zambia,ZMB,3691193326.08369,3945626806.80281,4596361145.52769,19888819424.0619,24445149303.3303,26269107774.6518,20349541094.6806,23489215309.9948,27196324765.3154
1084,"GNI, Atlas method (current US$)",NY.GNP.ATLS.CD,Zimbabwe,ZWE,4624842970.01213,4471990569.44914,4110330392.52782,12391182087.7093,14854556176.2828,16249407147.6579,24553581681.8257,28003360601.3528,29075307302.8481